// Code generated by sqlc. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"
)

type Good struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	Name      string       `json:"name"`
	Price     float64      `json:"price"`
}
