// Code generated by sqlc. DO NOT EDIT.

package model

import (
	"context"
)

type Querier interface {
	CreateGoods(ctx context.Context, arg CreateGoodsParams) (Good, error)
	DeleteGoods(ctx context.Context, arg DeleteGoodsParams) (Good, error)
	GetGoodsByID(ctx context.Context, id int64) (Good, error)
	GetGoodsByName(ctx context.Context, name string) (Good, error)
	UpdateGoods(ctx context.Context, arg UpdateGoodsParams) (Good, error)
}

var _ Querier = (*Queries)(nil)
