// Code generated by sqlc. DO NOT EDIT.
// source: inventory.sql

package model

import (
	"context"
	"time"
)

const createInventory = `-- name: CreateInventory :one
INSERT INTO "inventory"(goods,
                        sticks,
                        version)
VALUES ($1, $2, $3)
returning id, created_at, updated_at, deleted_at, goods, sticks, version
`

type CreateInventoryParams struct {
	Goods   int32 `json:"goods"`
	Sticks  int32 `json:"sticks"`
	Version int32 `json:"version"`
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, createInventory, arg.Goods, arg.Sticks, arg.Version)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Goods,
		&i.Sticks,
		&i.Version,
	)
	return i, err
}

const getInventoryByGoodsID = `-- name: GetInventoryByGoodsID :one
SELECT id, created_at, updated_at, deleted_at, goods, sticks, version
FROM "inventory"
WHERE goods = $1
LIMIT 1
`

func (q *Queries) GetInventoryByGoodsID(ctx context.Context, goods int32) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, getInventoryByGoodsID, goods)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Goods,
		&i.Sticks,
		&i.Version,
	)
	return i, err
}

const updateInventory = `-- name: UpdateInventory :one
update "inventory"
set updated_at = $1,
    sticks     = sticks + $3
where goods = $2
returning id, created_at, updated_at, deleted_at, goods, sticks, version
`

type UpdateInventoryParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	Goods     int32     `json:"goods"`
	Counts    int32     `json:"counts"`
}

func (q *Queries) UpdateInventory(ctx context.Context, arg UpdateInventoryParams) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, updateInventory, arg.UpdatedAt, arg.Goods, arg.Counts)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Goods,
		&i.Sticks,
		&i.Version,
	)
	return i, err
}
