// Code generated by sqlc. DO NOT EDIT.

package model

import (
	"context"
)

type Querier interface {
	CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error)
	GetInventoryByGoodsID(ctx context.Context, goods int32) (Inventory, error)
	UpdateInventory(ctx context.Context, arg UpdateInventoryParams) (Inventory, error)
}

var _ Querier = (*Queries)(nil)
