// Code generated by sqlc. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	// user email
	Email string `json:"email"`
	// user password
	Password string `json:"password"`
	// user nickname default email
	Nickname string `json:"nickname"`
	// male man ,female women
	Gender string `json:"gender"`
	// 1 user 2 admin
	Role int64 `json:"role"`
}
