// Code generated by sqlc. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"
)

type OrderGood struct {
	ID         int64        `json:"id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
	OrderID    int64        `json:"order_id"`
	GoodsID    int32        `json:"goods_id"`
	GoodsName  string       `json:"goods_name"`
	GoodsPrice float64      `json:"goods_price"`
	Nums       int32        `json:"nums"`
}

type OrderInfo struct {
	ID           int64           `json:"id"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	DeletedAt    sql.NullTime    `json:"deleted_at"`
	UserID       int32           `json:"user_id"`
	OrderID      int64           `json:"order_id"`
	PayType      sql.NullString  `json:"pay_type"`
	Status       int16           `json:"status"`
	TradeID      sql.NullString  `json:"trade_id"`
	OrderMount   sql.NullFloat64 `json:"order_mount"`
	PayTime      sql.NullTime    `json:"pay_time"`
	Address      string          `json:"address"`
	SignerName   string          `json:"signer_name"`
	SignerMobile string          `json:"signer_mobile"`
	Post         string          `json:"post"`
}

type ShoppingCart struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	UserID    int32        `json:"user_id"`
	GoodsID   int32        `json:"goods_id"`
	Nums      int32        `json:"nums"`
	Checked   bool         `json:"checked"`
}
